### ISSUE TITLE
Handler never uses "prio" arg

### ISSUE THREAD

**Issue by ncraike** [cmouse/pdns-remotebackend-python#4]
The `Handler` method [`record_prio_ttl()`](https://github.com/cmouse/pdns-remotebackend-python/blob/master/src/pdns/remotebackend/__init__.py#L22) takes a `prio` argument and doesn't use it for anything. Other `record...` methods call `record_prio_ttl()`, and some pass on a particular `prio` value.

I assume `prio` was intended to be the "priority" of the record, for `MX` and `SRV` records?

I can see from the [PowerDNS documentation](https://doc.powerdns.com/md/authoritative/backend-remote/#lookup) that the way "priority" is returned by backends has changed with 4.0:
> Note: priority field is required before 4.0, after 4.0 priority is added to content. This applies to any resource record which uses priority, for example SRV or MX.

To implement this behaviour, shouldn't the `record...()` methods either not take a priority argument, or take the priority argument and add it to `content`?

**Comment by cmouse** [comment]
I'll have to look into this.

**Comment by cmouse** [comment]
Closed via 0c7fde032c2d53c6c682d4987770b60435463348
